# typed: false
# frozen_string_literal: true

# IronClaw — security-hardened, self-hosted AI assistant platform.
#
# This formula is GENERATED by scripts/update-homebrew-formula.sh from a published
# release's SHA256SUMS — do not hand-edit the version/url/sha256 lines. To track a
# newer release, re-run that script and commit the result.
#
# Install:  brew tap IronSecCo/ironclaw https://github.com/IronSecCo/ironclaw
#           brew install ironsecco/ironclaw/ironclaw
#
# NOTE: homebrew-core ships an UNRELATED formula also named "ironclaw", and core
# wins the bare name. Always install the fully-qualified tap formula above; a bare
# "brew install ironclaw" would fetch the core package, not this one.
class Ironclaw < Formula
  desc "Security-hardened, self-hosted AI assistant platform (secured Go port)"
  homepage "https://github.com/IronSecCo/ironclaw"
  version "0.1.234"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.234/ironclaw_0.1.234_darwin_arm64.tar.gz"
      sha256 "02d67da849520e2343895768e381cc585d859b94c4e559334867e28a7ea8e91d"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.234/ironclaw_0.1.234_darwin_amd64.tar.gz"
      sha256 "7d9c99e0823de5afb35bc282ff80f266e18d746c567f4e0476debc2691f4230d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.234/ironclaw_0.1.234_linux_arm64.tar.gz"
      sha256 "a5af37809e3d05c0a128db7e6f03db512c794368e1cd6d2ab9e27776b2539d7a"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.234/ironclaw_0.1.234_linux_amd64.tar.gz"
      sha256 "84046d38da46d327b6b8c4b5ebd4b8be6bbd173522133a3ff99f48f1abd22c4f"
    end
  end

  def install
    bin.install "ironctl"
    bin.install "ironclaw-controlplane"
    bin.install "ironclaw-sandbox"
  end

  def caveats
    <<~EOS
      ironctl, ironclaw-controlplane, and ironclaw-sandbox are now on your PATH.

      Get started:
        ironctl version
        ironctl doctor      # preflight: model creds, toolchain, sockets

      For production the control plane usually runs as a container:
        ghcr.io/ironsecco/ironclaw-controlplane:v0.1.234
      See https://ironsecco.github.io/ironclaw/quickstart/ for the full first-run flow.
    EOS
  end

  test do
    assert_match "ironctl v#{version}", shell_output("#{bin}/ironctl version")
  end
end
