# typed: false
# frozen_string_literal: true

# IronClaw — security-hardened, self-hosted AI assistant platform.
#
# This formula is GENERATED by scripts/update-homebrew-formula.sh from a published
# release's SHA256SUMS — do not hand-edit the version/url/sha256 lines. To track a
# newer release, re-run that script and commit the result.
#
# Install:  brew tap IronSecCo/ironclaw https://github.com/IronSecCo/ironclaw
#           brew install ironsecco/ironclaw/ironclaw
#
# NOTE: homebrew-core ships an UNRELATED formula also named "ironclaw", and core
# wins the bare name. Always install the fully-qualified tap formula above; a bare
# "brew install ironclaw" would fetch the core package, not this one.
class Ironclaw < Formula
  desc "Security-hardened, self-hosted AI assistant platform (secured Go port)"
  homepage "https://github.com/IronSecCo/ironclaw"
  version "0.1.332"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.332/ironclaw_0.1.332_darwin_arm64.tar.gz"
      sha256 "df2d8842e8f3fd925b079c676ffa7c3793151daf8abf92cc066515a0cccf3b95"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.332/ironclaw_0.1.332_darwin_amd64.tar.gz"
      sha256 "d01dd619b05c794c2618c37c17e1cfa1bdb44612e82c529ec1d8bf6646108671"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.332/ironclaw_0.1.332_linux_arm64.tar.gz"
      sha256 "01d57e86769a7079f258e6ec6e26d2d5d82eb9e02a25b1da02744f6b4971ed5e"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.332/ironclaw_0.1.332_linux_amd64.tar.gz"
      sha256 "75290849e3e33fb959247300cfeec6e1f1326f1f272bfaae44f3144dcc7e7bfc"
    end
  end

  def install
    bin.install "ironctl"
    bin.install "ironclaw-controlplane"
    bin.install "ironclaw-sandbox"
  end

  def caveats
    <<~EOS
      ironctl, ironclaw-controlplane, and ironclaw-sandbox are now on your PATH.

      Get started:
        ironctl version
        ironctl doctor      # preflight: model creds, toolchain, sockets

      For production the control plane usually runs as a container:
        ghcr.io/ironsecco/ironclaw-controlplane:v0.1.332
      See https://ironsecco.github.io/ironclaw/quickstart/ for the full first-run flow.
    EOS
  end

  test do
    assert_match "ironctl v#{version}", shell_output("#{bin}/ironctl version")
  end
end
