# typed: false
# frozen_string_literal: true

# IronClaw — security-hardened, self-hosted AI assistant platform.
#
# This formula is GENERATED by scripts/update-homebrew-formula.sh from a published
# release's SHA256SUMS — do not hand-edit the version/url/sha256 lines. To track a
# newer release, re-run that script and commit the result.
#
# Install:  brew tap IronSecCo/ironclaw https://github.com/IronSecCo/ironclaw
#           brew install ironsecco/ironclaw/ironclaw
#
# NOTE: homebrew-core ships an UNRELATED formula also named "ironclaw", and core
# wins the bare name. Always install the fully-qualified tap formula above; a bare
# "brew install ironclaw" would fetch the core package, not this one.
class Ironclaw < Formula
  desc "Security-hardened, self-hosted AI assistant platform (secured Go port)"
  homepage "https://github.com/IronSecCo/ironclaw"
  version "0.1.109"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.109/ironclaw_0.1.109_darwin_arm64.tar.gz"
      sha256 "16faa0848c356ae397dc47231f8960290883260e21e985eac2e8d7ca2faa793c"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.109/ironclaw_0.1.109_darwin_amd64.tar.gz"
      sha256 "dfbde9a559ab59d68dc4abaa35e59daf67b33d5cb9604bc410dbc0e7a9c8d21a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.109/ironclaw_0.1.109_linux_arm64.tar.gz"
      sha256 "e3f116370181a14a42883674feb555fd4c40d8083833ab6e9da4032d8537f3db"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.109/ironclaw_0.1.109_linux_amd64.tar.gz"
      sha256 "0194f9692a5e9b55b858c543828e101813566c7e8f17207748db8dac3fdf0384"
    end
  end

  def install
    bin.install "ironctl"
    bin.install "ironclaw-controlplane"
    bin.install "ironclaw-sandbox"
  end

  def caveats
    <<~EOS
      ironctl, ironclaw-controlplane, and ironclaw-sandbox are now on your PATH.

      Get started:
        ironctl version
        ironctl doctor      # preflight: model creds, toolchain, sockets

      For production the control plane usually runs as a container:
        ghcr.io/ironsecco/ironclaw-controlplane:v0.1.109
      See https://ironsecco.github.io/ironclaw/quickstart/ for the full first-run flow.
    EOS
  end

  test do
    assert_match "ironctl v#{version}", shell_output("#{bin}/ironctl version")
  end
end
