#!/usr/bin/env bash
# Regenerate the Homebrew formula (Formula/ironclaw.rb) from a published release.
#
#   scripts/update-homebrew-formula.sh [TAG]
#
# With no argument it resolves the latest release; pass a tag (e.g. v0.1.80) to pin
# a specific one. The SHA-256 of every binary archive is read from the release's
# signed-over SHA256SUMS — the same trust anchor install.sh uses — so the formula
# never carries a checksum that wasn't published with the release. Run it after a
# release you want the `brew install` path to track, then commit the result.
#
# Requires: gh (authenticated) OR a public release + curl, and shasum/sha256sum.
set -euo pipefail

REPO="${IRONCLAW_REPO:-IronSecCo/ironclaw}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/Formula/ironclaw.rb"

say()  { printf '==> %s\n' "$*"; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

TAG="${1:-}"
if [ -z "$TAG" ]; then
  say "Resolving latest release of ${REPO}"
  TAG="$(gh release view --repo "$REPO" --json tagName -q .tagName)" \
    || die "could not resolve latest release (is gh authenticated?)"
fi
VERSION="${TAG#v}"
say "Pinning formula to ${TAG} (version ${VERSION})"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT INT TERM

# Pull SHA256SUMS straight from the release — the trust anchor, not a recomputation.
if gh release download "$TAG" --repo "$REPO" --pattern SHA256SUMS --dir "$tmp" 2>/dev/null; then
  :
else
  curl -fsSL "https://github.com/${REPO}/releases/download/${TAG}/SHA256SUMS" -o "$tmp/SHA256SUMS" \
    || die "could not fetch SHA256SUMS for ${TAG}"
fi

# sum <archive-name> -> the sha256 recorded in SHA256SUMS (fail closed if absent).
sum() {
  local name="$1" got
  got="$(grep -F "$name" "$tmp/SHA256SUMS" | awk '{print $1}' | head -n1 || true)"
  [ -n "$got" ] || die "no SHA256SUMS entry for ${name} — is ${TAG} fully published?"
  printf '%s' "$got"
}

DARWIN_ARM64="$(sum "ironclaw_${VERSION}_darwin_arm64.tar.gz")"
DARWIN_AMD64="$(sum "ironclaw_${VERSION}_darwin_amd64.tar.gz")"
LINUX_ARM64="$(sum "ironclaw_${VERSION}_linux_arm64.tar.gz")"
LINUX_AMD64="$(sum "ironclaw_${VERSION}_linux_amd64.tar.gz")"

base="https://github.com/${REPO}/releases/download/${TAG}"

mkdir -p "${ROOT}/Formula"
# NOTE: this is an UNQUOTED heredoc so ${VERSION}/${TAG}/${base}/${sha} expand. Do
# NOT put backticks or $(...) in the template below — the shell would execute them.
# Ruby string interpolation (#{version}, #{bin}) is safe (no leading $).
cat > "$OUT" <<EOF
# typed: false
# frozen_string_literal: true

# IronClaw — security-hardened, self-hosted AI assistant platform.
#
# This formula is GENERATED by scripts/update-homebrew-formula.sh from a published
# release's SHA256SUMS — do not hand-edit the version/url/sha256 lines. To track a
# newer release, re-run that script and commit the result.
#
# Install:  brew tap IronSecCo/ironclaw https://github.com/IronSecCo/ironclaw
#           brew install ironsecco/ironclaw/ironclaw
#
# NOTE: homebrew-core ships an UNRELATED formula also named "ironclaw", and core
# wins the bare name. Always install the fully-qualified tap formula above; a bare
# "brew install ironclaw" would fetch the core package, not this one.
class Ironclaw < Formula
  desc "Security-hardened, self-hosted AI assistant platform (secured Go port)"
  homepage "https://github.com/IronSecCo/ironclaw"
  version "${VERSION}"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "${base}/ironclaw_${VERSION}_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM64}"
    end
    on_intel do
      url "${base}/ironclaw_${VERSION}_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD64}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/ironclaw_${VERSION}_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
    on_intel do
      url "${base}/ironclaw_${VERSION}_linux_amd64.tar.gz"
      sha256 "${LINUX_AMD64}"
    end
  end

  def install
    bin.install "ironctl"
    bin.install "ironclaw-controlplane"
    bin.install "ironclaw-sandbox"
  end

  def caveats
    <<~EOS
      ironctl, ironclaw-controlplane, and ironclaw-sandbox are now on your PATH.

      Get started:
        ironctl version
        ironctl doctor      # preflight: model creds, toolchain, sockets

      For production the control plane usually runs as a container:
        ghcr.io/ironsecco/ironclaw-controlplane:${TAG}
      See https://ironsecco.github.io/ironclaw/quickstart/ for the full first-run flow.
    EOS
  end

  test do
    assert_match "ironctl v#{version}", shell_output("#{bin}/ironctl version")
  end
end
EOF

say "Wrote ${OUT}"
say "Pinned archives (sha256 from ${TAG} SHA256SUMS):"
printf '  darwin/arm64  %s\n' "$DARWIN_ARM64"
printf '  darwin/amd64  %s\n' "$DARWIN_AMD64"
printf '  linux/arm64   %s\n' "$LINUX_ARM64"
printf '  linux/amd64   %s\n' "$LINUX_AMD64"
